version: "2.1"

dependencies: ./nightly-project-dependencies.yaml

pre: |
  export PME_CMD="java -jar ${{ env.PME_CLI_PATH }} -s ${{ env.PME_MAVEN_SETTINGS_XML }} -DallowConfigFilePrecedence=true -DprojectSrcSkip=false"
  echo "PME_CMD=${{ env.PME_CMD }}"
  export BUILD_MVN_OPTS="${{ env.BUILD_MVN_OPTS }} -s ${{ env.PME_MAVEN_SETTINGS_XML }}"
  echo "BUILD_MVN_OPTS=${{ env.BUILD_MVN_OPTS }}"
  export REMOVE_MODULES="./productized/remove_modules.sh ./productized/modules"
  echo "REMOVE_MODULES=${{ env.REMOVE_MODULES }}"

default:
  build-command:
    current: mvn clean install -Dproductized=true -DskipTests=true ${{ env.BUILD_MVN_OPTS }}
    upstream: mvn clean install -Dquickly -Dproductized=true -DskipTests=true ${{ env.BUILD_MVN_OPTS }} 
    downstream: mvn clean install -Dquickly -Dproductized=true -DskipTests=true ${{ env.BUILD_MVN_OPTS }} 
    after:
      current: |
        podman system prune -f

build:
  - project: kiegroup/drools
    build-command:
      upstream: |
        ${{ env.PME_CMD }} ${{ env.PME_ALIGNMENT_PARAMS_kiegroup_drools }}
        bash -c "set -e ; set -o pipefail ; ${{ env.REMOVE_MODULES }} ; ${{ env.PME_BUILD_SCRIPT_kiegroup_drools }} ${{ env.BUILD_MVN_OPTS }} | tee ${{ env.WORKSPACE }}/drools.maven.log"

  - project: kiegroup/kogito-runtimes
    build-command:
      current: |
        ${{ env.PME_CMD }} ${{ env.PME_ALIGNMENT_PARAMS_kiegroup_kogito_runtimes }}
        bash -c "set -e ; set -o pipefail ; ${{ env.REMOVE_MODULES }} ; ${{ env.PME_BUILD_SCRIPT_kiegroup_kogito_runtimes }} ${{ env.BUILD_MVN_OPTS }} | tee ${{ env.WORKSPACE }}/kogito_runtimes.maven.log"

  - project: kiegroup/kogito-apps
    build-command:
      downstream: |
        ${{ env.PME_CMD }} ${{ env.PME_ALIGNMENT_PARAMS_kiegroup_kogito_apps }}
        bash -c "set -e ; set -o pipefail ; ${{ env.REMOVE_MODULES }} ; ${{ env.PME_BUILD_SCRIPT_kiegroup_kogito_apps }} ${{ env.BUILD_MVN_OPTS }} | tee ${{ env.WORKSPACE }}/kogito_apps.maven.log"

  - project: kiegroup/kogito-examples
    build-command:
      downstream: |
        ${{ env.PME_CMD }} ${{ env.PME_ALIGNMENT_PARAMS_kiegroup_kogito_examples }}
        bash -c "set -e ; set -o pipefail ; ${{ env.REMOVE_MODULES }} ; ${{ env.PME_BUILD_SCRIPT_kiegroup_kogito_examples }} ${{ env.BUILD_MVN_OPTS }} | tee ${{ env.WORKSPACE }}/kogito_examples.maven.log"

  - project: kiegroup/kie-tools
    build-command:
      downstream: |
        ${{ env.PME_CMD }} ${{ env.PME_ALIGNMENT_PARAMS_kiegroup_kie_tools }}
        bash -c "set -o pipefail ; ${{ env.PME_BUILD_SCRIPT_kiegroup_kie_tools }} ${{ env.BUILD_MVN_OPTS }} | tee ${{ env.WORKSPACE }}/kie_tools.maven.log"

  - project: kiegroup/kogito-images
    build-command:
      downstream: |
        export MAVEN_OPTIONS="-s ${{ env.PME_MAVEN_SETTINGS_XML }}"
        echo "MAVEN_OPTIONS=${{ env.MAVEN_OPTIONS }}"
        export NIGHTLY="true"
        echo "NIGHTLY=${{ env.NIGHTLY }}"
        export NIGHTLY_DEPLOY_FOLDER="${{ env.WORKSPACE }}/deployDirectory"
        echo "NIGHTLY_DEPLOY_FOLDER=${{ env.NIGHTLY_DEPLOY_FOLDER }}"
        ${{ env.PME_CMD }} ${{ env.PME_ALIGNMENT_PARAMS_kiegroup_kogito_images }}
        bash -c "set -o pipefail ; ${{ env.PME_BUILD_SCRIPT_kiegroup_kogito_images }} ${{ env.BUILD_MVN_OPTS }} | tee ${{ env.WORKSPACE }}/kogito_images.maven.log"

  - project: kubesmarts/kie-tools
    build-command:
      downstream: |
        echo "Cloned kubesmarts/kie-tools repository for building the images"

  - project: kiegroup/kogito-serverless-operator
    build-command:
      downstream: |
        echo "Cloned kiegroup/kogito-serverless-operator repository for building Operator image"
